server:
  port: 5201 # todo 端口
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.194.148.139:3306/project_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: nanshuo
    password: nanshuo
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 42.194.148.139
    port: 6379
    timeout: 5000
    # todo 若你的 Redis 需要密码，请打开注释，并填写密码
    password: nanshuo
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''

# 接口文档配置(prod环境设置密码访问或者关闭等等)
knife4j:
  basic:
    enable: true
    username: prod
    password: prod